baseURL = "/"
languageCode = "en-us"
DefaultContentLanguage = "en"

title = "Enterprise Partner Portal"
theme = "hugo-theme-docdock"
# themesdir = "../.."

publishDir = "public/"

[params]
# editURL = "https://github.com/vjeantet/hugo-theme-docdock/edit/master/exampleSite/content/"
showVisitedLinks = false # default is false
themeStyle = "flex" # "original" or "flex" # default "original"
themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = false # default is false
disableSearch = false # default is false
disableNavChevron = true # set true to hide next/prev chevron, default is false

[taxonomies]
  tag = "tags"
  category = "categories"


[outputs]
home = [ "HTML", "RSS", "JSON"]


[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-bookmark'></i> aventurineco.com"
identifier = "ds"
url = "https://google.com"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-bullhorn'></i> Aventurine Support"
url = "https://google.com"
weight = 11

[[menu.shortcuts]]
name = "<i class='fa fa-bookmark'></i> Aventurine Product Training"
url = "https://google.com"
weight = 20

[[menu.shortcuts]]
name = "<i class='fa fa-bookmark'></i> Services Portal"
url = "https://google.com"
weight = 30



# English is the default language
defaultContentLanguage = "en"
# Force to have /en/my-page and /fr/my-page routes, even for default language.
defaultContentLanguageInSubdir= false

[Languages]
[Languages.en]
title = "Aventurine North America"
weight = 1
languageName = "North America"


[Languages.uk]
title = "Aventurine Europe"
weight = 2
languageName = "Europe"


